const actions ={
    ADD_ITEM :'ADD_ITEM',
    REMOVE_ITEM : 'REMOVE_ITEM',
    SET_ITEMS : 'SET_ITEMS',
    FETCH_ITEMS_FAIL : 'FETCH_ITEMS_FAIL',

    SET_ORDERS : 'SET_ORDERS',
    SET_ORDERS_FAIL : 'SET_ORDERS_FAIL',
    SET_ORDERS_START : 'SET_ORDERS_START',

    PURCHASE_CLOTH_START : 'PURCHASE_CLOTH_START',
    PURCHASE_CLOTH_SUCCESS : 'PURCHASE_CLOTH_SUCCESS',
    PURCHASE_CLOTH_FAIL : 'PURCHASE_CLOTH_FAIL',
    PURCHASE_INIT : 'PURCHASE_INIT',

    AUTH_START : 'AUTH_START',
    AUTH_SUCCESS : 'AUTH_SUCCESS',
    AUTH_FAIL : 'AUTH_FAIL',
    AUTH_LOGOUT : 'AUTH_LOGOUT'
}

export default actions;